- name: Execute python with cleanup
  block:
    - name: Copy the Python script to the target machine
      copy:
        src: "{{ script_name }}"
        dest: "{{ script_name }}"
        mode: '0755'

    - name: Execute the Python script
      command: python3 "{{ script_name }}"
      register: script_output
      failed_when: script_output.rc != 0

    - name: Print the script's output
      debug:
        msg: "{{ script_output.stdout }}"
      when: script_output is defined

  always:
    - name: Clean up
      file:
        path: "{{ script_name }}"
        state: absent